server:
  port: 8090

eureka:
  server:
    enableSelfPreservation: true
  instance:
    appname: MY-EUREKA-SERVER
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8090/eureka
